import Link from "next/link";

export const metadata = {
  title: "Blogs | My Next App",
  description: "Generated by my next app",
};

const blogs = [
  {
    id: 1,
    year: 2023,
    title: "Blog 1"
  },
  {
    id: 2,
    year: 2022,
    title: "Blog 2"
  },
  {
    id: 3,
    year: 2025,
    title: "Blog 3"
  },
  {
    id: 4,
    year: 2024,
    title: "Blog 4"
  },
  {
    id: 5,
    year: 2023,
    title: "Blog 5"
  },
  {
    id: 6,
    year: 2024,
    title: "Blog 6"
  },
]

const BlogsPage = () => {
    return (
        <div className="container mx-auto">
          {
            blogs.map(({ id, year, title }) =>
              <Link
                key={id}
                href={{
                  pathname: `/blogs/${year}/${id}`,
                  query: {
                    title: title
                  }
                }}
                className="block border border-blue-500 p-2 m-4">{title}
              </Link>
            )
          }
        </div>
    );
};

export default BlogsPage;