import Link from "next/link";

export const metadata = {
  title: "Blogs | My Next App",
  description: "Generated by my next app",
};

// const blogs = [
//   {
//     id: 1,
//     year: 2023,
//     title: "Blog 1"
//   },
//   {
//     id: 2,
//     year: 2022,
//     title: "Blog 2"
//   },
//   {
//     id: 3,
//     year: 2025,
//     title: "Blog 3"
//   },
//   {
//     id: 4,
//     year: 2024,
//     title: "Blog 4"
//   },
//   {
//     id: 5,
//     year: 2023,
//     title: "Blog 5"
//   },
//   {
//     id: 6,
//     year: 2024,
//     title: "Blog 6"
//   },
// ]

const BlogsPage = async () => {
  // fetch data directly
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const blogs = await res.json();

    return (
        <div className="container mx-auto">
          {
            blogs.map(({ id, title, body }) =>
              <div key={id} className="border border-blue-500 p-2 m-4">
                <h2 className="text-2xl">{id}. {title}</h2>
                <p>{body}</p>
                <Link href={`/blogs/${id}`} className="inline-block mt-5">
                  <button className="text-white bg-blue-500 px-2 py-1">Details</button>
                </Link>
              </div>

            )
          }
        </div>
    );
};

export default BlogsPage;