import LoadBlogData from "@/utils/LoadBlogData";
import Link from "next/link";

export const metadata = {
  title: "Blogs | My Next App",
  description: "Generated by my next app",
};

const BlogsPage = async () => {
  // fetch data from function
  const blogs = await LoadBlogData(); 
  // await is mandatory here

    return (
        <div className="container mx-auto">
          {
            blogs.map(({ id, title, body }) =>
              <div key={id} className="border border-blue-500 p-2 m-4">
                <h2 className="text-2xl">{id}. {title}</h2>
                <p>{body}</p>
                <Link href={`/blogs/${id}`} className="inline-block mt-5">
                  <button className="text-white bg-blue-500 px-2 py-1">Details</button>
                </Link>
              </div>

            )
          }
        </div>
    );
};

export default BlogsPage;