export const metadata = {
  title: "Blogs | My Next App",
  description: "Generated by my next app",
};

const BlogsPage = () => {
  return (
    <div>
      Welcome to blog page
    </div>
  );
};

export default BlogsPage;