export const metadata = {
  title: "About | My Next App",
  description: "Generated by my next app",
};

const AboutPage = () => {
    return (
        <div>
            This is About page.
        </div>
    );
};

export default AboutPage;