export const metadata = {
  title: "Add Product | Dashboard | My Next App",
  description: "Generated by my next app",
};

const AddProductPage = () => {
    return (
        <div>
            Add product form this Page.
        </div>
    );
};

export default AddProductPage;