import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Next App",
  description: "Generated by my next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <li>
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/blogs">Blogs</a>
            <a href="/dashboard">Dashboard</a>
          </li>
        </nav>
        {children}
        <footer>Footer</footer></body>
    </html>
  );
}

export default RootLayout;