import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto(
  {
    subsets: ["latin"],
    weight: ["400", "500", "700", "900"]
  });

export const metadata = {
  title: "My Next App",
  description: "Generated by my next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        </body>
    </html>
  );
}

export default RootLayout;