export const metadata = {
  title: "Manage Product | Dashboard | My Next App",
  description: "Generated by my next app",
};

const ManageProductPage = () => {
  return (
    <div>
      Manage all the products from here.
    </div>
  );
};

export default ManageProductPage;