import MySidebar from "@/components/MySidebar";

export const metadata = {
  title: "Dashboard | My Next App",
  description: "Generated by next app",
};

const DashboardLayout = ({children}) => {
  return (
    <div className="flex mx-40 my-10">
      <MySidebar />
      {children}
    </div>
  );
};

export default DashboardLayout
;