export const metadata = {
  title: "Dashboard | My Next App",
  description: "Generated by my next app",
};

const DashboardLayout = ({children}) => {
    return (
        <div>
            <div>Sidebar</div>
            {children}
        </div>
    );
};

export default DashboardLayout
;